name: Dotnet Core React CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.x"

      - name: Build
        run: dotnet build

      - name: Test
        run: |
          dotnet test

      - name: Publish
        run: |
          dotnet publish -c Release -o ./publish
